apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: default
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - env:
        - name: "TZ"
          value: "Europe/Istanbul"
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        image: redis:latest
        name: redis
      restartPolicy: Always
