apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: default
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: "26379"
    port: 26379
    targetPort: 26379
  selector:
    app: redis-sentinel
status:
  loadBalancer: {}
